[package]
name = "solana-asset-manager"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
actix-web = "4.4"
actix-files = "0.6"
env_logger = "0.10"
log = "0.4"

[profile.release]
opt-level = 3
lto = true