[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = false
release = false

[watch]
watch = ["src", "index.html", "styles.css"]

[serve]
address = "0.0.0.0"
port = 8080

[clean]
dist = "dist"